name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: ":rocket: Features"
    labels:
      - 'Feature'
  - title: ":+1: Adding Pages"
    labels:
      - 'Page'
  - title: ":memo: Wording correction"
    labels:
      - 'Correction'
  - title: ":bug: Bug Fixes"
    labels:
      - bug
  - title: ":fire: Remove"
    labels:
      - 'Remove'
  - title: ":recycle: Refactoring"
    labels:
      - 'Refactoring'
  - title: ":white_check_mark: Testing"
    labels:
      - 'Testing'
  - title: ":green_heart: CI/CD"
    labels:
      - 'CI/CD'
  - title: ":up: Dependencies"
    labels:
      - 'Dependencies'
  - title: ":cop: Security"
    labels:
      - 'Security'
  - title: ":gear: Development"
    labels:
      - 'Development'
  - title: ":book: Documentation"
    labels:
      - documentation
  - title: Other Changes
    labels:
      - "*"
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: "patch"

template: |
  ## Changes

  $CHANGES
