name: Build the beamer PDF image

on:
  workflow_call:

jobs:
  build:
    name: Build the beamer PDF  image
    runs-on: ubuntu-24.04
    container:
      image : ghcr.io/ichmy55/opencae-slides/texcomp:main
      options: --user 1001:118
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Get latest release tag
        id: get_tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repo = context.repo;
            const { data } = await github.rest.repos.getLatestRelease({
                owner: repo.owner,
                repo: repo.repo,
            });
            let tag = data.tag_name;
            console.log(data)
            const regex = /sprint(\d+)/;
            const match = tag.match(regex);
            if (match) {
              const sprintNumber = parseInt(match[1]);
              tag = sprintNumber + 1;
            }
            return tag;
      - name: "Overwrite the VERSION.txt"
        run: |
          echo 'sprint${{ steps.get_tag.outputs.result }}' > VERSION.txt
      - name: "build PDF"
        run:  make localbuild
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: dist-pdf
          path: dist/**
          retention-days: 5
