name: Build the beamer PDF image

on:
  workflow_call:

jobs:
  build:
    name: Build the beamer PDF  image
    runs-on: ubuntu-24.04
    container:
      image : ghcr.io/ichmy55/opencae-slides/texcomp:main
      options: --user 1001:118
    steps:
      - name: "Checkout  repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Overwrite the VERSION.txt"
        run:  git describe --abbrev=0 --tags | tee VERSION.txt
      - name: "build PDF"
        run:  make localbuild
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: dist-pdf
          path: dist/**
          retention-days: 5
