name: Build the beamer PDF image

on:
  workflow_call:

jobs:
  build:
    name: Build the beamer PDF  image
    runs-on: ubuntu-24.04
    container:
      image : ghcr.io/ichmy55/opencae-slides/texcomp:main
      options: --user 1001:118
    steps:
      - name: "Checkout  repository"
        uses: actions/checkout@v4
      - name: get tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: "Overwrite the VERSION.txt"
        run: |
          echo "${TAG_NAME}"
          echo "${{ env.TAG_NAME }}"
          echo "${{ env.TAG_NAME }}" > VERSION.txt
      - name: "build PDF"
        run:  make localbuild
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: dist-pdf
          path: dist/**
          retention-days: 5
