name: On push Actions

on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build the beamer PDF  image
    runs-on: ubuntu-24.04
    container:
      image : ghcr.io/ichmy55/opencae-slides:main
    steps:
      - name: "Test"
        run:  |
          ls -al
          cat /etc/passwd
          who
