name: On push Actions

on:
  push:
    branches:
      - development

jobs:
  lint:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/textlint.yml
  build-pdf:
    uses: ./.github/workflows/build-pdf.yml
