name: On push Actions

on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build the beamer PDF  image
    runs-on: ubuntu-24.04
    container:
      image : ghcr.io/ichmy55/opencae-slides:main
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    steps:
      - name: "Test"
        run:  |
          echo ---
          pwd
          echo ---
          ls -al
          echo ---
          ls -al ../
          echo ---
          cat /etc/passwd
          echo ---
          who
          echo ---
          echo qwe > qwe.txt
          echo ---
          ls -al
          echo ---
