name: develop pull request

on:
  pull_request:
    branches:
      - development

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint-reviewdog:
    uses: ./.github/workflows/actionlint-reviewdog.yml
  hadolint-reviewdog:
    uses: ./.github/workflows/hadolint-reviewdog.yml
  checkmake-action:
    uses: ./.github/workflows/checkmake-action.yml

  textlint-reviewdog:
    needs: [actionlint-reviewdog]
    uses: ./.github/workflows/textlint-reviewdog.yml
