name: GitHub Actions Demo

on: [push,workflow_dispatch]

jobs:
  echo_hello:
    runs-on: ubuntu-24.04
    steps: 
      - name: "挨拶"
        run: echo "Nice to meet you!!"

      - name: "名前を言う"
        run: echo "My Name is Taro!!"

      - name: "趣味を話す"
        run: echo "I love programming!!"

      - name: "別れの挨拶をする"
        run: echo "Good Bye!!"
