name: main-pull request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  textlint-reviewdog:
    uses: ./.github/workflows/textlint-reviewdog.yml
