name: Build the package for compiling latex files.

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build the docker image for compiling latex files
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout  repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v10.1

      - name: "Set up Docker Buildx"
        if: contains(steps.changed-files.outputs.all_modified_files, 'Dockerfile')
        uses: docker/setup-buildx-action@v3
 
      - name: "Container registry に認証する"
        if: contains(steps.changed-files.outputs.all_modified_files, 'Dockerfile')
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Extract metadata (tags, labels) for Docker"
        if: contains(steps.changed-files.outputs.all_modified_files, 'Dockerfile')
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/texcomp
 
      - name: "Docker ビルド & プッシュ"
        if: contains(steps.changed-files.outputs.all_modified_files, 'Dockerfile')
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
