name: Release Drafter

on:
  workflow_call:
    outputs:
      update_url:
        description: "Update URL of pdf"
        value: ${{ jobs.release_draft.outputs.update_url }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release_draft:
    runs-on: ubuntu-24.04
    outputs:
      update_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: create_release
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: main
          publish: true
      - name: test
        run: |
          echo qwe1
          pwd
          echo qwe2
          ls -l
          echo qwe4
          echo  ${{ steps.create_release.outputs.upload_url }}
          echo qwe5
