name: reviewdog

on: [pull_request]

jobs:
  lint:
    name: textlint
    runs-on: ubuntu-24.04
    permissions:
      checks: write
      contents: read
      pull-requests: write
    container:
      image : ghcr.io/ichmy55/opencae-slides/textlint:main
      options: --user 1001:118
    steps:
      - name: "Checkout  repository"
        uses: actions/checkout@v4
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: "Textlint & prh"
        run:  make local-lint
      - name: run  reviewdog
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat .textlint.log | reviewdog -reporter=github-pr-review -efm='%f:%l:%c:%m'
