name: reviewdog

on: [pull_request]

jobs:
  lint:
    name: textlint
    runs-on: ubuntu-24.04
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - name: "Checkout  repository"
        uses: actions/checkout@v4
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: inst
        run:  |
          apt -y install nodejs npm
          npm install -g textlint textlint-plugin-latex2e textlint-rule-preset-japanese textlint-rule-preset-ja-spacing textlint-filter-rule-comments textlint-rule-prh
      - name: "Textlint & prh"
        run:  npx textlint README.md  > ./.textlint.log
      - name: run  reviewdog
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat .textlint.log 
          cat .textlint.log | reviewdog -reporter=github-pr-review -efm='%f:%l:%c:%m'
