name: Upload the beamer PDF image to release

on:
  workflow_call:
    inputs:
      name_pdf:
        description: Name of the pdf
        required: true
        type: string

jobs:
  upload-pdf:
    name: Upload the beamer PDF  image to release
    runs-on: ubuntu-24.04
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: dest_pdf
      - name: Extract the pdf
        run: |
          pwd
          echo qwe1
          ls -l
          echo qwe2
          echo ${{ inputs.name_pdf }}
          echo qwe3
