name: Upload the beamer PDF image to release

on:
  workflow_call:

jobs:
  upload-pdf:
    name: Upload the beamer PDF  image to release
    runs-on: ubuntu-24.04
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: dest_pdf
      - name: Extract the pdf
        run: |
          pwd
          ls -l
          file *
          echo ${{ env.DEST_PDF }}
          echo ${{ env }}
          echo qwe
