name: textlint

on:
  workflow_call:

jobs:
  lint:
    name: textlint
    runs-on: ubuntu-24.04
    permissions:
      checks: write
      contents: read
      pull-requests: write
    container:
      image : ghcr.io/ichmy55/opencae-slides/textlint:main
      options: --user 1001:118
    steps:
      - name: "Checkout  repository"
        uses: actions/checkout@v4
      - name: "Textlint & prh"
        run:  make local-lint
