name: Upload the beamer PDF image to release

on:
  workflow_call:

jobs:
  upload-pdf:
    name: Upload the beamer PDF  image to release
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: dest_pdf
      - name: get the pdf name
        run:  make name >> $GITHUB_ENV
      - name: test
        run: |
          echo qwe1
          echo  ${{ secrets.GITHUB_TOKEN }}
          echo qwe2
          echo  ${{ env.DEST_PDF }}
          echo qwe3
          echo  ${{ env.UPLOAD_URL }}
          echo qwe4
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./dest_pdf/${{ env.DEST_PDF }}
          asset_name: ${{ env.DEST_PDF }}
          asset_content_type: application/pdf
